services:
  - type: web
    name: smart-trashbin-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0